#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/artem/.Xmodmap"

# set background image, although I used to not need this line
fbsetbg /home/artem/EveningGlowKDE.jpg

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
unclutter -idle 2 &
# idesk &
ipager -c /home/artem/.ipager/temach_green.conf &
nm-applet --sm-disable &
# dolphin4 &
dolphin ~/Desktop/Uni/ &
# run notification daemon for notify-send/twmnc
twmnd &
# battery indicator
cbatticon --critical-level=10 --low-level=15 --update-interval=180 --command-critical-level='/home/artem/temach-arch-linux/battery_warn.sh' &
# konversation &
urxvt &
urxvt &
parcellite &
redshift &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/artem/.fluxbox/log"
