# see: https://github.com/pufferffish/wireproxy 
WGConfig = /home/artem/Downloads/wireguard-moon.conf

# http creates a http proxy on your LAN, and all traffic would be routed via wireguard.
[http]
BindAddress = 127.0.0.1:8080
