# see: https://github.com/rvaiya/keyd/blob/master/docs/keyd.scdoc
[ids]
*

[main]
capslock = layer(control)

# left meta key always emits "leftmeta"
# right meta key always emits "leftmeta + leftshift"
# transform meta into ctrl to resize window with one hand using -/+ keys
meta = layer(mylayer)

# "ctrl" + "=" zooms in without shift (its "ctrl" + "+")
[control]
= = +
	
[mylayer]
# undo shift keypress that autofollows, to emit just a single ctrl
shift = layer(control)
