# see: https://askubuntu.com/questions/1466286/lenovo-yoga-slim-7-pro-volume-cannot-be-changed
# see: https://forum.endeavouros.com/t/no-sound-control-yoga-pro-14-imh9/57335/2
options snd_sof_intel_hda_generic hda_model=alc287-yoga9-bass-spk-pin
